### ISSUE TITLE
Feedback for basisghana

### ISSUE THREAD

**Issue by sskorik01** [openwashdata/basisghana#4]
Hi, can you have a look at the README and let me know what you think? Thank you!

**Comment by larnsce** [comment]
Great work, thank you. I like it a lot. 

The only question I have is why you chose a log scale for the figure? Something you could try is to turn the percentages into categories (e.g. 4 with 25% per step) and then use 5 colours with increasing colour scale to show which regions are in which category.

**Comment by sskorik01** [comment]
Thank you. Since the data is distributed in an uneven way (most of the values are around 8%, but there are some low values around 0-1%), the logarithmic scale helps visualizing the differences better. I tried with linear categories but then, the differences are not enhanced. I will add a short explanation for the logarithmic scale.
