### ISSUE TITLE
GH pages website does not render

### ISSUE THREAD

**Issue by larnsce** [openwashdata/basisghana#5]
@sskorik01: could you check what's happening here?

https://openwashdata.github.io/basisghana/

**Comment by sskorik01** [comment]
The build and deploy, more specifically the build with Jekyll part does not work. It's a conversion error but I'm not sure where to act on it

Configuration file: none
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/style.scss':
                    No such file or directory @ dir_chdir - /github/workspace/docs

**Comment by larnsce** [comment]
The `docs` folder was in the `.gitignore` file. That can happen with one of the `pkgdown` functions. I have seen that before. Should be fixed now:

https://github.com/openwashdata/basisghana/commit/5dc5bf18c66b953e6f2b7b912f1cd21593f8a104
